on: [push]
env:
  name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate random quotes
        id: rose
        run: |
          source $(pwd)/rose.sh
          echo "start_status_quote=$(random_quote)" >> $GITHUB_OUTPUT
          echo "final_status_quote=$(random_quote)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Prepare deployment notification
        id: notes
        uses: ./
        with:
          text: |
            ## What's Changed
            * [List Item 1](http://example.com)
            * List Item 2

      - id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # The following message update step does not accept a channel name.
          # Setting a channel ID here for consistency is highly recommended.
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "*${{ steps.rose.outputs.start_status_quote }}*",
              "attachments": [
                {
                  "author_name": "${{ github.actor }}",
                  "author_link": "${{ github.server_url }}/${{ github.actor }}",
                  "author_icon": "${{ github.server_url }}/${{ github.actor }}.png?size=32",
                  "color": "${{ fromJSON('{ success: "good", failure: "danger", cancelled: "gray" }')[job.status] }}",
                  "title": "*${{ env.name }} deployment started.*",
                  "text": ${{ toJSON(steps.notes.outputs.text) }},
                  "thumb_url": "https://avatars.slack-edge.com/2022-04-01/3354706307424_3c366bf2570e82087e09_512.jpg",
                  "footer": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      # - uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     # Unlike the step posting a new message, this step does not accept a channel name.
      #     # Please use a channel ID, not a name here.
      #     channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
      #     # update-ts: ${{ steps.slack.outputs.ts }}
      #     # "text": "Deployment finished (Completed)",
      #     payload: |
      #       {
      #         "attachments": [
      #           {
      #             "pretext": "Deployment finished",
      #             "color": "28a745",
      #             "fields": [
      #               {
      #                 "title": "Status",
      #                 "short": true,
      #                 "value": "Completed"
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
